DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS POST_TAG;
DROP TABLE IF EXISTS TAG;
DROP TABLE IF EXISTS POST;

CREATE TABLE IF NOT EXISTS POST (
    ID BIGSERIAL PRIMARY KEY,
    TITLE VARCHAR(500) NOT NULL,
    TEXT TEXT NOT NULL,
    LIKES_COUNT INTEGER DEFAULT 0 NOT NULL,
    COMMENTS_COUNT INTEGER DEFAULT 0 NOT NULL,
    IMAGE VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_POST_TITLE ON POST(TITLE);

CREATE TABLE IF NOT EXISTS COMMENT (
    ID BIGSERIAL PRIMARY KEY,
    POST_ID BIGINT NOT NULL,
    TEXT TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (POST_ID) REFERENCES POST(ID) ON DELETE CASCADE
);
CREATE INDEX IDX_COMMENT_POST_ID ON COMMENT(POST_ID);

CREATE TABLE IF NOT EXISTS TAG (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE
);
CREATE INDEX IDX_TAG_NAME ON TAG(NAME);

CREATE TABLE IF NOT EXISTS POST_TAG (
    POST_ID BIGINT NOT NULL,
    TAG_ID BIGINT NOT NULL,
    PRIMARY KEY (POST_ID, TAG_ID),
    FOREIGN KEY (POST_ID) REFERENCES POST(ID) ON DELETE CASCADE,
    FOREIGN KEY (TAG_ID) REFERENCES TAG(ID) ON DELETE CASCADE
);
CREATE INDEX IDX_POST_TAG_TAG_ID ON POST_TAG(TAG_ID);
CREATE INDEX IDX_POST_TAG_POST_ID ON POST_TAG(POST_ID);